<?php

namespace Tests;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication, DatabaseTransactions;

    public $token;
    public $header;
    public $headerLogin;
    public function signIn($data=['username'=>'30355511', 'password'=>'123456'])
    {
        $response = $this->post('/api/login', $data);

        $content = json_decode($response->getContent());

        $this->assertObjectHasAttribute('access_token', $content, 'Token does not exists');
        $this->token = $content->access_token;
        $this->header = ['[Accept] => application/json', 'Authorization' => 'Bearer ' . $this->token];
        $this->headerLogin = ['[Accept] => application/json'];
        return $this;
    }

    public function signOut()
    {
        $response = $this->post('/api/logout', [], ['Authorization' => 'Bearer '. $this->token]);
        $content = json_decode($response->getContent());

//        $this->token = null;
        return $content;
    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->signIn();
    }
    protected function tearDown()
    {
        $this->signOut();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
